In [12]:
#importing the libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#importing the dataset.
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:,2:-1].values
Y = dataset.iloc[:,4:].values

#splitting the dataset into trainingset and testset.
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

#feature scalling.
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler();
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

# need the Logistic model for classification.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)

#Prediction here.
y_pred = classifier.predict(x_test)

#Making with the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

C:\Users\su\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\su\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
#importing the libraries.
import numpy as np
import pandas as pd

In [39]:
#importing the dataset.
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:,2:-1].values
Y = dataset.iloc[:,4].values

In [40]:
#first 10 rows of the data
dataset.iloc[:10,:]


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [41]:
#splitting the dataset into trainingset and testset.
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [42]:
print("X_train")
print(x_train[:10,:])
print("\n")

X_train
[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]]




In [45]:
print("Y_train")
print(y_train[:10])
print("\n")

Y_train
[0 1 0 1 1 1 0 0 0 0]




In [46]:
#feature scalling.
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler();
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [50]:
# Logistic model for classification.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,np.array(y_train))
print("")

In [54]:

#Prediction here.
y_pred = classifier.predict(x_test)

#Making with the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)


In [55]:
cm

array([[65,  3],
       [ 8, 24]], dtype=int64)

cm

array([[65,  3],
       [ 8, 24]], dtype=int64)